INSERT INTO RESEARCHERS ("NAME", "LAST_NAME", "EMAIL", "DATE_OF_BIRTH", "TELEPHONE_NUMBER", "WEBSITE") VALUES 
    ('Rene', 'Svetina', 'rene.svetina@gmail.com', '1987-10-09', '+38640663494', 'raziskovalec.org');

INSERT INTO RESEARCHERS ("NAME", "LAST_NAME", "EMAIL", "DATE_OF_BIRTH", "TELEPHONE_NUMBER", "WEBSITE") VALUES 
    ('Janez', 'Novak', 'janez.novak@gmail.com', NULL, '+38641559632', NULL);

INSERT INTO RESEARCHERS ("NAME", "LAST_NAME", "EMAIL", "DATE_OF_BIRTH", "TELEPHONE_NUMBER", "WEBSITE") VALUES 
    ('Andrej', 'Lep', 'andrej.lep@gmail.com', NULL, '+38641558963', NULL);

INSERT INTO RESEARCHERS ("NAME", "LAST_NAME", "EMAIL", "DATE_OF_BIRTH", "TELEPHONE_NUMBER", "WEBSITE") VALUES 
    ('Ime1', 'Priimek1', 'email1@email.com', NULL, NULL, NULL);

INSERT INTO RESEARCHERS ("NAME", "LAST_NAME", "EMAIL", "DATE_OF_BIRTH", "TELEPHONE_NUMBER", "WEBSITE") VALUES 
    ('Ime2', 'Priimek2', 'email2@email.com', NULL, NULL, NULL);

INSERT INTO RESEARCHERS ("NAME", "LAST_NAME", "EMAIL", "DATE_OF_BIRTH", "TELEPHONE_NUMBER", "WEBSITE") VALUES 
    ('Ime3', 'Priimek3', 'email3@email.com', NULL, NULL, NULL);

INSERT INTO RESEARCHERS ("NAME", "LAST_NAME", "EMAIL", "DATE_OF_BIRTH", "TELEPHONE_NUMBER", "WEBSITE") VALUES 
    ('Ime4', 'Priimek4', 'email4@email.com', NULL, NULL, NULL);

INSERT INTO RESEARCHERS ("NAME", "LAST_NAME", "EMAIL", "DATE_OF_BIRTH", "TELEPHONE_NUMBER", "WEBSITE") VALUES 
    ('Ime5', 'Priimek5', 'email5@email.com', NULL, NULL, NULL);

INSERT INTO RESEARCHERS ("NAME", "LAST_NAME", "EMAIL", "DATE_OF_BIRTH", "TELEPHONE_NUMBER", "WEBSITE") VALUES 
    ('Ime6', 'Priimek6', 'email6@email.com', NULL, NULL, NULL);

INSERT INTO RESEARCHERS ("NAME", "LAST_NAME", "EMAIL", "DATE_OF_BIRTH", "TELEPHONE_NUMBER", "WEBSITE") VALUES 
    ('Ime7', 'Priimek7', 'email7@email.com', NULL, NULL, NULL);

INSERT INTO RESEARCHERS ("NAME", "LAST_NAME", "EMAIL", "DATE_OF_BIRTH", "TELEPHONE_NUMBER", "WEBSITE") VALUES 
    ('Ime8', 'Priimek8', 'email8@email.com', NULL, NULL, NULL);

INSERT INTO RESEARCHERS ("NAME", "LAST_NAME", "EMAIL", "DATE_OF_BIRTH", "TELEPHONE_NUMBER", "WEBSITE") VALUES 
    ('Ime9', 'Priimek9', 'email9@email.com', NULL, NULL, NULL);

COMMIT;